### ISSUE TITLE
Upload Manager error on multiple files

### ISSUE THREAD

**Issue by Manuelandro** [oracle/oci-typescript-sdk#100]
During the deployment I have to upload a folder with 1000+ files 

```
;(function () {
   // walk is a function to recursively read sundirectories and files
    walk('./build', async (err, res) => {
        for (const entry of res) {
            const objectName = `${entry[0]}`

            try {
                uploadManager
                    .upload({
                        content: {
                            filePath: join('./build', entry[0]),
                        },
                        requestDetails: {
                            bucketName: BUCKET,
                            objectName: objectName,
                            namespaceName: NAMESPACE
                        },
                    })
                    .then(() => console.log(`Uploaded ${objectName}`))
            } catch (err) {
                console.log(err)
            }
        }
    })
})()
```

in console I have this output for almost every file
```

putObject failed, will retry. Last known error: Error: request to https://objectstorage.us-ashburn-1.oraclecloud.com/n/id93c1ew8b1b/b/frontend-build-it/o/assets%2Fimages%2Fflags%2F4x3%2Fgm.svg failed, reason: Client network socket disconnected before secure TLS connection was established
All retry attempts have exhausted. Total Attempts : 1. Last exception occurred : Error: request to https://objectstorage.us-ashburn-1.oraclecloud.com/n/id93c1ew8b1b/b/frontend-build-it/o/assets%2Fimages%2Fflags%2F4x3%2Far.svg failed, reason: Client network socket disconnected before secure TLS connection was established
```

I've tried with the await uploadManager()... as in the example files, it works but for my use case it takes hours to upload the entire folder

**Comment by waruwaruwaru** [comment]
Hi @Manuelandro, this is a known issue at the moment and we are working on releasing a fix for file based streams that should improve the performance. What version of the SDK are you using?

**Comment by Manuelandro** [comment]
> Hi @Manuelandro, this is a known issue at the moment and we are working on releasing a fix for file based streams that should improve the performance. What version of the SDK are you using?

Thanks for the replay. I'm currently using    oci-common@^2.4.0 and oci-objectstorage@^2.4.0

**Comment by waruwaruwaru** [comment]
Hi @Manuelandro the latest SDK should help with your performance. And I think that the upload should have an await or else your node task will try to upload all 1000+ files at once which might cause a lot of memory usage and fail.
