### ISSUE TITLE
oci-objectstorage TypeScript type definition error: Interface 'UploadableBlob' incorrectly extends interface 'Blob'

### ISSUE THREAD

**Issue by wilsonzlin** [oracle/oci-typescript-sdk#108]
I'm getting this error when compiling a TypeScript application that uses oci-objectstorage:

```
node_modules/oci-objectstorage/lib/upload-manager/uploadable-blob.d.ts:6:18 - error TS2430: Interface 'UploadableBlob' incorrectly extends interface 'Blob'.
  The types returned by 'stream()' are incompatible between these types.
    Type 'ReadableStream<any>' is missing the following properties from type 'ReadableStream': readable, read, setEncoding, pause, and 22 more.

6 export interface UploadableBlob extends Blob {
                   ~~~~~~~~~~~~~~
```

Versions:
- oci-common: ^2.6.1
- oci-objectstorage: ^2.6.1
- typescript: ^4.4.4

**Comment by waruwaruwaru** [comment]
Hi @wilsonzlin, what version of Node are you using? At the moment we only support version 14.X https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/typescriptsdk.htm#Versions_Supported

**Comment by wilsonzlin** [comment]
Thanks for letting me know, I'm using 16.x currently. Will there be support for newer Node.js versions in the near future? It does appear to only be a TypeScript type definitions issue.

**Comment by waruwaruwaru** [comment]
Hey @wilsonzlin, we do have Node version 16 support in our backlog. We don't have an ETA for this yet but it is something that we are looking to support.

**Comment by wilsonzlin** [comment]
OK thanks, appreciate the details 👍
