### ISSUE TITLE
No matching version found for oci-datalabelingservice@2.8.0

### ISSUE THREAD

**Issue by jmpolvera** [oracle/oci-typescript-sdk#110]
Environment:
Windows 10 Pro -> WSL Ubuntu 20
node version: v10.19.0
npm version: 6.14.4

Doing `npm install oci-sdk`  causes npm dependency error:

Error: 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for oci-datalabelingservice@2.8.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'oci-sdk'
npm ERR! notarget

**Comment by jodoglevy** [comment]
Thanks for reporting - we'll take a look

**Comment by waruwaruwaru** [comment]
Hi @jmpolvera the package is now published in npm. Can you give the installation another try? Please feel free to reopen this ticket if you are still hitting the issue.
