### ISSUE TITLE
oci-objectstorage::PutObjectRequest `content-length` is not optional

### ISSUE THREAD

**Issue by laberin** [oracle/oci-typescript-sdk#12]
oci-objectstorage@1.2.2

I guess it should be optional as [python-sdk](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html#oci.object_storage.ObjectStorageClient.put_object)

```
const putObjectRequest: PutObjectRequest = {
  namespaceName: 'namespace123',
  bucketName: 'bucket-blabla',
  objectName: 'newfilename.txt`,
  contentLength: ?, // cannot decide the content-length
  putObjectBody: file.stream, // file.stream is stream type
}
```

**Comment by waruwaruwaru** [comment]
contentLength is now an optional parameter. SDK will auto-calculate contentLength if user does not provide it.
