### ISSUE TITLE
Add an example for your new AI Speech service

### ISSUE THREAD

**Issue by gregmsanderson** [oracle/oci-typescript-sdk#154]
Hello,

From https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/typescriptsdkexamples.htm

> If you'd like to see another example not already covered, file a [GitHub issue](https://github.com/oracle/oci-typescript-sdk/issues).

So here I am :) I see your OCI AI Speech went GA back in March 2022 so it would be nice if there was an example of how to call it using the SDK (JavaScript).

**Comment by KartikShrikantHegde** [comment]
Hi @gregmsanderson ,

Thanks for reporting the issue.

We do have examples for APIs of the AI Speech service. Here is an example of how to create a transcription job. More examples are on the same tree page for different APIs.

https://docs.oracle.com/en-us/iaas/api/#/en/speech/20220101/TranscriptionJob/CreateTranscriptionJob

Thanks.

**Comment by gregmsanderson** [comment]
Ah, ok. Thanks.
