### ISSUE TITLE
Error get ReadableStream from ObjectStorageClient on nodejs 18.7.0

### ISSUE THREAD

**Issue by DeepzUa** [oracle/oci-typescript-sdk#155]
Hi on nodejs 18.7.0 bug from get ReadableStream from ObjectStorageClient.

I use the getObject function and get this message:

(node:12872) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

And I got this response 
`ReadableStream { locked: false, state: 'readable', supportsBYOB: false }`

But if i use nodejs 16.16.+ version, i receive normal stream

`
PassThrough {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: [Object], tail: [Object], length: 1 },
    length: 1956,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: true,
    constructed: true,
    sync: false,
    needReadable: true,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
`

**Comment by KartikShrikantHegde** [comment]
Closing this ticket as NodeJS 16.x version would help solve this issue.

**Comment by Rudecruels** [comment]
@KartikShrikantHegde  NodeJS 20.x also gives the same output 
ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
