### ISSUE TITLE
[fix][README] Feedback link deactivated. 

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-typescript-sdk#163]
The link on README is found deactivated.
```
Are you a Developer using the OCI SDK? If so, please fill out our survey to help us make the OCI SDK better for you. [Click here](https://oracle.questionpro.com/t/APeMlZka26?custom3=npmjs).
```

Believing that the survey has ended, it is time to remove it.

**Comment by KartikShrikantHegde** [comment]
Hi @davidkhala,

Thank you for reporting this issue. We will take out the link.

Thanks.

**Comment by waruwaruwaru** [comment]
Feedback link is now removed. Please feel free to re-open this issue if there are any more questions or concern.
