### ISSUE TITLE
Are there any alternatives to for OCI config file?

### ISSUE THREAD

**Issue by samuelastech** [oracle/oci-typescript-sdk#175]
I'm receiving the credentials dynamically through HTTP, there is no config file. So, the following code won't work for me:

```typescript
const provider: common.ConfigFileAuthenticationDetailsProvider = new common.ConfigFileAuthenticationDetailsProvider();
const client = new identity.IdentityClient({ authenticationDetailsProvider: provider });
```

I need to set up the `ConfigFileAuthenticationDetailsProvider` in another way.

I found this [doc](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm) that says:

> If you're using one of the Oracle SDKs or tools, supply the required credentials in either a configuration file or a **config object** in the code.

How could I authenticate by passing a config object instead of a config file?

**Comment by jodoglevy** [comment]
@samuelastech  I think you'd want to use the SimpleAuthenticationDetailsProvider. See the following for examples:
- https://github.com/oracle/oci-typescript-sdk/blob/5515a7c03ecf5e719512bee3a870c4344668a52e/examples/javascript/simple-authentication.js
- https://github.com/oracle/oci-typescript-sdk/blob/5515a7c03ecf5e719512bee3a870c4344668a52e/examples/typescript/simple-authentication.ts

**Comment by samuelastech** [comment]
Thanks, that is what I was looking for.
