### ISSUE TITLE
How to estimate cost through API? 

### ISSUE THREAD

**Issue by samuelastech** [oracle/oci-typescript-sdk#180]
I see the [Cloud Cost Estimator](https://www.oracle.com/br/cloud/costestimator.html) tool and I would like to interact with it through API -- given a list of instances return the total cost. Is it possible? Can't find anything in the docs.

**Comment by KartikShrikantHegde** [comment]
Hi @samuelastech, the cost estimator tool doesn't have a public API to interact with. 

We do have a list price API that is documented here: https://docs.oracle.com/en-us/iaas/Content/GSG/Tasks/signingup_topic-Estimating_Costs.htm#accessing_list_pricing

**Comment by KartikShrikantHegde** [comment]
Hi @samuelastech , closing this ticket for now based on my above comments. Please feel free to reopen if you need more info.

**Comment by samuelastech** [comment]
Hi @KartikShrikantHegde, I do need more info.

The price list doesn't have information about E2 instances but I do need it because there are some instances on my side. Where could I get this information?

**Comment by KartikShrikantHegde** [comment]
Hi @samuelastech , I will ask the service team to review your ask.

**Comment by samuelastech** [comment]
Ok, thanks. I will be waiting

**Comment by samuelastech** [comment]
If I could find the `skuPartNumber` of a given OCID, my problem would be solved...
The UsageAPI brings it to me sometimes, but not always.

**Comment by KartikShrikantHegde** [comment]
Hi @samuelastech , Did you give the above API a try? 

I am going to close this ticket for now, please feel free to re-open if you still face issues. Thanks.
