### ISSUE TITLE
Can't get error information when request failed

### ISSUE THREAD

**Issue by jeiea** [oracle/oci-typescript-sdk#182]
When `new IdentityClient(config).listCompartments({ compartmentId: '...' })`, I got this.

```
Request failed with Exception : [object Object]
Retrying request -> Total Attempts : 1, Retrying after 1.891 seconds...
```

I expect a more specific output than [object Object].

**Comment by waruwaruwaru** [comment]
Hey @jeiea, can you try wrapping the API call in a try/catch block, on the catch block, put a break point on the error object thats coming in? Sometimes when you console.log the error object it shows [object Object]. Another thing you can try is JSON.stringify the error object and then console log the JSON.stringify's result.

**Comment by jeiea** [comment]
I remember that logging was not controlled by me. Maybe I can adjust retry count and catch without retry.

If you think it is not a bug and design, then close this.

**Comment by waruwaruwaru** [comment]
The SDK should return the error object to you when you catch the error with or without retry. The error object you get back from the SDK will contain the error information, though if you console.log the error, JavaScript will sometimes log out [object Object]. A way to how the actual object is to JSON.stringify the error object.
