### ISSUE TITLE
HELP WITH AUTHENTICATION ERROR

### ISSUE THREAD

**Issue by mateuscs3003** [oracle/oci-typescript-sdk#202]
I tried to list the volume groups with node.js, but returned some volume groups and during the process, returned an error from authentication, and then not returned all the volume groups. There's a picture from the error in a linux terminal. 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/90486314/231796114-95949e2b-a7de-4d19-acd6-cfba11fbc39d.png)

**Comment by josethz00** [comment]
Up! Getting similar errors but with the oci-object-storage service using the AWS S3 Compatibility API

**Comment by jodoglevy** [comment]
Can each person getting errors here please paste the code which reproduces the error, as well as the full error stack trace?

A `NotAuthorizedOrNotFound` error indicates that the user making the request does not have sufficient permissions to perform the action requested, or that the resource the action was requested to be performed on does not exist.

For a permissions case, please evaluate the permissions granted to the account being used to make the request, to make sure the account has been given sufficient permissions.

For the resource does not exist case, please check the resource name(s) / id(s) being passed in the request, to make sure they are the correct name(s) / id(s) of the resources you are trying to perform an action on.

**Comment by KartikShrikantHegde** [comment]
Hi @samuelastech @josethz00 @mateuscs3003 I am closing this ticket as we haven't heard back in a while. Please feel free to re-open the ticket if you are still facing the issue. Thanks.
