### ISSUE TITLE
Specifying a custom path to `ConfigFileAuthenticationDetailsProvider`  doesn't work

### ISSUE THREAD

**Issue by josethz00** [oracle/oci-typescript-sdk#203]
I have tried to specify many paths to my oracle config file, tried to use it with the config file located in the default location, but nothing works. Is there any extra config that I need to do?

PS: Compatibility API with AWS also not working for aws-sdkjs

[Info About `ConfigFileAuthenticationDetailsProvider`](https://docs.oracle.com/pt-br/iaas/Content/API/SDKDocs/typescriptsdkconcepts.htm)

**Comment by KartikShrikantHegde** [comment]
Hi @josethz00 , Following up on my request above. Please let us know if you are still facing the issue and provide us with the above details so that we can take a look. Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @josethz00 , I will be closing this ticket for now, please feel free to re-open it if you are still facing the issue. Thanks.
