### ISSUE TITLE
Missed call to circuitBreaker.shutdown()

### ISSUE THREAD

**Issue by bohdand-weka** [oracle/oci-typescript-sdk#244]
In our project we've found high CPU usage from OCI SDK.

After investigation we've found that reason is circuitbreaker. By disabling it CPU usage was ok.

In our codebase we're using object-storage-client, like this:
```
func getClient() {
   return new ObjectStorageClient({authenticationDetailsProvider: provider})
}
```
So for many requests we're having many client instances with circuitbreaker for each.
Circuitbreaker has timers which has to be cleaned up after `ObjectStorageClient` is not in use by calling `_circuitBreaker.shutdown()`.

So we need `ObjectStorageClient.shutdown()` method to be implemented as well

**Comment by jyotisaini** [comment]
@bohdand-weka Thanks for reporting the issue. Circuit breaker timers are reset once the circuit breaker is close. Are yo saying for each client the circuit breaker remains open leading to high CPU usage ?

**Comment by bohdand-weka** [comment]
@jyotisaini it looks like so, we're working on fixing the issue on our side - even the client gets GC'ed - timers aren't going to reset

**Comment by jyotisaini** [comment]
Let us know if it works once you fix issue at your end and if you need further assistance.

**Comment by JoshuaWR** [comment]
Hi @bohdand-weka, I wanted to check in again and ask if you have fixed the issue, or if you have learned anything else about it from your end. Thank you!

**Comment by bohdand-weka** [comment]
@JoshuaWR we've have to apply the patch to `ObjectStorageClient` to call shutdown manually, so it fixed the issue for us

**Comment by bohdand-weka** [comment]
I has to expose `_circuitBreaker` and call it's `shutdown()` method when `ObjectStorageClient` is not needed, but for you I guess you'll better to implement `shutdown()` method on your own and update doc that users must to call it for cleanup

**Comment by JoshuaWR** [comment]
@bohdand-weka could you point me towards this shutdown() method that you are mentioning? I'm failing to find it within the repository. Is this a method that you've written yourself, and if so could you share how you are using it? Thanks!

**Comment by JoshuaWR** [comment]
Hi again @bohdand-weka, please refer to the latest release of the SDK, which now includes a method in each client which allows the user to shut down the circuit breaker once it is no longer needed. An example of this method can be found [here](https://github.com/oracle/oci-typescript-sdk/blob/master/examples/typescript/circuit-breaker.ts#L62). Please let us know if this fixes the issue you were facing, thank you!

**Comment by bohdand-weka** [comment]
@JoshuaWR looks cool, we will try it in near future, thanks!

**Comment by JoshuaWR** [comment]
@bohdand-weka Have you had a chance to try this change out yet? Can I close this ticket for you? Thanks!

**Comment by bohdand-weka** [comment]
@JoshuaWR I'm pretty sure we can close the ticket, everything looks good!
