### ISSUE TITLE
Alloy config

### ISSUE THREAD

**Issue by mariusrak** [oracle/oci-typescript-sdk#251]
Hi, I get an error 
```
Alloy config file not found at [object Object], enabling all OCI services as default
```

There for sure should not be the `[object Object]`. It's because of this:

```
        "Alloy config file not found at " +
          { configFilePath } +
          ", enabling all OCI services as default"
```
The `{` `}` around `configFilePath` should not be there

Second thing is, that I don't want to provide that file, can I configure the SDK by some parameter to some constructor? Thanks

**Comment by jyotisaini** [comment]
Thanks for reporting this issue, @mariusrak. We are currently working on a fix for this.

**Comment by shlomoweb1** [comment]
Hey, I would like to know if there is a way for the SDK not to request any of the alloys; it slows down my express loading and all stuff configured.env file by me

**Comment by jyotisaini** [comment]
Hi @shlomoweb1 this issue has been fixed in the latest version of the SDK. Please upgrade the SDK and you will no longer see alloy related loading/messages.

**Comment by jyotisaini** [comment]
This issue has been fixed.
