### ISSUE TITLE
How to execute examples

### ISSUE THREAD

**Issue by hiriumi** [oracle/oci-typescript-sdk#41]
I've written Python scripts using OCI Python SDK quite a bit but I am relatively new to executing Typescript/Javascript though I have experiences in very old JavaScript. It would be great to show how to execute samples. And I think it would be great to mention to have the `~/.oci/config` file ready or at least mention that `OCI CLI` setup is a prerequisite.

It would also be nice to learn how one can start to contribute. What are the prerequisites? What kind of environment would you recommend? If this is something I could contribute by doing research, I will do so. I would like to contribute! :)

**Comment by waruwaruwaru** [comment]
Hi @hiriumi, refer to this page for running examples: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/typescriptsdkexamples.htm

**Comment by hiriumi** [comment]
@waruwaruwaru 
That does it. Thank you very much! 👍
