### ISSUE TITLE
Conflict with Kubernetes client

### ISSUE THREAD

**Issue by ricardo-kagawa** [oracle/oci-typescript-sdk#43]
It is generally considered bad practice to mutate the prototype of a native object, probably because it often causes unintended far-reaching side-effects.

https://github.com/oracle/oci-typescript-sdk/blob/v1.10.0/lib/common/lib/waiter.ts#L13

In my case, it breaks the [Kubernetes client](https://www.npmjs.com/package/@kubernetes/client-node)'s JSON serializer. As a matter of fact, them iterating over `Array`s and `Object`s using `for..in` is not much better, but adding an enumerable property to the `Array` prototype is definitely worse.

I don't know what this method is used for, so I can't give a definitive solution, but a quick workaround would be to define the method as a [non-enumerable property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) instead, so that it is at least not listed in `for..in` loops.

**Steps for reproduction**

1. Create a minimal project with `@kubernetes/client-node` and `oci-sdk` as dependencies.
2. Make sure you have a Kubernetes cluster running (maybe in OCI Container Engine).
3. Import both clients, then attempt to query K8s API for any resource. Notice in this case that map-like objects list an additional `undefined` property with `undefined` value that should not exist. Also notice that list-like objects list an additional empty element that should not exist.
4. Import both clients (if not already), then attempt to create a resource in K8s API. The operation will likely fail, because map-like objects will include an additional `undefined` property with an `undefined` value (unlikely to be rejected, but possible), and list-like objects will include an extra empty element (which is likely to be rejected).

**What is expected**

Accessing Kubernetes API with or without the OCI client in the same application should yield the same results. Namely, K8s resources should not list an additional invalid property, nor additional empty elements. In other words, accessing Kubernetes API in OCI Container Engine and other resources in OCI (perhaps to manage them as Kubernetes resources) from the same application should work properly.

For the record, this is their serializer:

https://github.com/kubernetes-client/javascript/blob/0.13.2/src/gen/model/models.ts#L1823

**Comment by waruwaruwaru** [comment]
@ricardo-kagawa thank you for the information. Would you happen to have the error message? It looks like our code is mutating the prototype of the native object which causes this issue. I will be taking a look into this 👍

**Comment by ricardo-kagawa** [comment]
It does not exactly throw errors from within `oci-sdk` itself, or even from within `@kubernetes/client-node`. Instead, the presence of `oci-sdk` causes `@kubernetes/client-node` to send invalid requests to Kubernetes API server, which then proceeds to reject the operation with Kubernetes API error messages (a JSON object coming with an HTTP 400 status, describing the API validation error). I doubt the exact error message would be helpful, but any Kubernetes API operation that mutates resources and validates fields (especially those containing lists) would end up rejected. In the absence of `oci-sdk`, no errors occur, and requested operations succeed.

But for your convenience, I have **already tracked** where the Array prototype is mutated. Please **open the first link** in the issue description.

My quick and dirty workaround was to delete the extraneous property, then redefine it in the prototype itself using a non-enumerable property. The proper solution though would be to replace the method in the Array prototype for an unbound function, but that might be a sizable change. A proof of fix would be to ensure the extraneous `exists` method (or any other extraneous method) is not listed when performing `for..in` loops in any regular array.

**Comment by waruwaruwaru** [comment]
@ricardo-kagawa the latest SDK should no longer modify Array.prototype. This should resolve the issue with Kubernetes client-node package. Thank you for pointing this out. Feel free to reopen this issue if the problem is still occurring on the latest version of the SDK.
