### ISSUE TITLE
How to get the value of an ORACLE Vault Secret? 

### ISSUE THREAD

**Issue by nochmu** [oracle/oci-typescript-sdk#48]
I would like to get the value of an Oracle Vault Secret from inside an Oracle Function . 
Like this: [in Java](https://blogs.oracle.com/developers/protect-your-sensitive-data-with-secrets-in-the-oracle-cloud) or this [in Python](https://github.com/oracle/oracle-functions-samples/tree/master/samples/oci-vault-get-secret-python)

In the examples I find only one example, if I send the encrypted value as a request. 
But in the above case the encrypted value is stored in the vault...

**Comment by waruwaruwaru** [comment]
Hi @nochmu, 
The TypeScript SDK's secret client should have this same API. Its the getSecretBundle API.
Here is an example https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/1.14.0/secrets/GetSecretBundle.ts.html

**Comment by waruwaruwaru** [comment]
Have not heard from customer. Will close this issue. Please re-open this issue if you still have trouble. Thank you.
