### ISSUE TITLE
oci-objectstorage putObject with files larger than 128K

### ISSUE THREAD

**Issue by nicholasgiles** [oracle/oci-typescript-sdk#50]
We are uploading files to OCI object storage from file streams (created with fs.createReadStream) using the oci-objectstorage putObject method. This is failing for files larger than 128K with the error message:

request to https://objectstorage.us-phoenix-1.oraclecloud.com/n/xxxxxxxxxxxx/b/xxxxx/o/file.bin failed, reason: socket hang up

According to the official example at https://github.com/oracle/oci-typescript-sdk/blob/master/examples/javascript/objectstorage.js we should use a NodeFSBlob object with the highWatermark parameter set to the file size.

Doing this resolves the error message above for >128K files but at the expense of loading the entire file into memory, which causes problems for large files. For example, a 1.7G file causes the Node process to be killed with an out of memory error.

Equally, using fs.createReadStream(path, {highWaterMark: stats.size}) and passing this stream to putObject gives the same behavior as described in the previous paragraph.

In any case, we don't want to load the entirety of files that we're about to upload to OCI OS into memory first, which is why we were using streams.

Our situation is that we are in the progress of migrating our Node.js code from the AWS SDK (S3 compatibility mode) to the native OCI SDK - we did not have this issue when using the AWS SDK.

Node version: 12.18.2
oci-objectstorage version: 1.14.0

**Comment by jyotisaini** [comment]
Hi @nicholasgiles Thanks for reporting this. We will look into it. For the large files we have an upload manager that handles uploading large files in parts. Can you try uploading files using Upload-manager. https://github.com/oracle/oci-typescript-sdk/blob/master/examples/javascript/uploadmanager.js  ?

**Comment by nicholasgiles** [comment]
@jyotisaini Thanks - does UploadManager support streams (which we have a use case for)? The example seems only to be using files in the filesystem.

**Comment by jyotisaini** [comment]
@nicholasgiles Unfortunately upload manager does expect files from the filesystem and internally converts to streams and uploads in parts. How were you using NodeFsBlob ? It also expects file path. You can pass the same path that you were using to create stream (fs.createReadStream(**path**) and upload manager will create stream chunks accordingly and upload it to the ObjectStorage. You can find more details here https://github.com/oracle/oci-typescript-sdk/tree/master/lib/objectstorage/lib/upload-manager.

**Comment by nicholasgiles** [comment]
We have two use cases. For files that already exist in the filesystem, we're using code of the form:

const stats = fs.statSync(fileLocation);
const nodeFsBlob = new os.NodeFSBlob(fileLocation, stats.size);
const objectData = await nodeFsBlob.getData();

as per https://github.com/oracle/oci-typescript-sdk/blob/master/examples/javascript/objectstorage.js

In our other use case where we pass the stream directly, we've been setting putObjectBody (in the putObjectRequest) to the stream reference passed into our methods. According to https://github.com/oracle/oci-typescript-sdk/blob/master/lib/objectstorage/lib/request/put-object-request.ts, putObjectBody is of type Blob | stream.Readable | ReadableStream | string.

**Comment by waruwaruwaru** [comment]
I believe the 1.7GB file might be too big for 1 upload in NodeJS. https://stackoverflow.com/questions/8974375/whats-the-maximum-size-of-a-node-js-buffer. It will need to be broken into chunks. I will look into the file streams (created with fs.createReadStream) scenario. Thanks for reporting this. @nicholasgiles

**Comment by nicholasgiles** [comment]
@waruwaruwaru Thanks for the update. The example (https://github.com/oracle/oci-typescript-sdk/blob/master/examples/javascript/objectstorage.js) says 2GB is the limit. Even if we're not dealing with such large files, the fact we seemingly need to buffer the entire file into memory in order to use putObject is not great for us.

**Comment by waruwaruwaru** [comment]
@nicholasgiles Can you try giving specifying the highWaterMark, start and end when you create the stream? i.e:

  const fileLocation = "/Users/rustyshackleford/Documents/Random/testFile";
  const stats = fs.statSync(fileLocation);
  const stream = fs.createReadStream(fileLocation, {
    highWaterMark: stats.size,
    start: 0,
    end: stats.size
  });

And then pass stream to the putObjectBody.

**Comment by nicholasgiles** [comment]
@waruwaruwaru As per my original comment, we have already tried this (specifying highWaterMark) and it works for smaller files (~130K in size). There are however two problems with this approach:

1. File appears to be loaded into memory, causing out-of-memory issues for larger files. We can accept a chunk of 64K at a time (for example) being loaded into memory during the upload but not the entire file.
2. For streams that are not coming directly from a file on the disk, we don't know the file size beforehand.

**Comment by waruwaruwaru** [comment]
Object Storage's Multipart Upload API might help achieve what you want. It can take chunks of data from your stream and upload it. You can upload the chunks in parallel.
https://docs.oracle.com/en-us/iaas/api/#/en/objectstorage/20160918/MultipartUpload/UploadPart

Although currently our Upload Manager example takes in a file from a file path, you may be able to re-use the same code for a stream.
https://github.com/oracle/oci-typescript-sdk/blob/master/lib/objectstorage/lib/upload-manager/upload-manager.ts#L159
Here is the interface for the UploadPart API: https://github.com/oracle/oci-typescript-sdk/blob/master/lib/objectstorage/lib/request/upload-part-request.ts

**Comment by nicholasgiles** [comment]
We've previously been using the AWS SDK with OCI OS (in S3 compatibility mode) and this has worked OK for us (using s3.upload), so we'll revert to using this for the time being. We don't want to switch to multipart uploads at this time as for the most part our files are not that big.

@waruwaruwaru @jyotisaini Do you plan to fix putObject (for the two issues in https://github.com/oracle/oci-typescript-sdk/issues/50#issuecomment-776249101)?

**Comment by jyotisaini** [comment]
Hi @nicholasgiles we do plan to handle the use cases you mentioned in our Upload manager. We will open a task for this and update you once it has been fixed.

**Comment by waruwaruwaru** [comment]
Hi @nicholasgiles, our latest SDK (v1.20.1) should now be able to handle large files with putObject (keep in mind the 2GB limitation on a 64bit machine from NodeJS) without knowing the size beforehand. You can call putObject without specifying the content-length and the SDK should now be able to calculate it on its own. Let me know if this works or if there is any issues that you run into. Additionally, you can also use Upload Manager's .upload() function (which is similar to AWS SDK's .upload() function). This will upload the stream in chunks. We have an example of using Upload Manager that you can refer to: https://github.com/oracle/oci-typescript-sdk/blob/master/examples/typescript/uploadmanager.ts but you can modify this example to pass in your stream instead of giving a filePath. The code block would look like this:
````
await uploadManager.upload({            
  content: {              
    stream: myStreamObj  // myStreamObj is the stream object coming from your end.        
  },            
  requestDetails: {              
    namespaceName: namespaceName,              
    bucketName: bucketName,              
    objectName: objectName            
  }          
});
````

**Comment by nicholasgiles** [comment]
@waruwaruwaru Thanks for this - I've given it a quick test and it does appear to be working. Will let you know if we find any issues when moving this into production.

**Comment by nicholasgiles** [comment]
@waruwaruwaru Further testing has found that if we set a value for "contentLength" then this causes a regression in the behavior of "putObject" and the "socket hang up" error returns for >128K files.

As a workaround, simply excluding "contentLength" from the parameter passed to "putObject" is OK for us, but this seems like a bug to me.

**Comment by waruwaruwaru** [comment]
@nicholasgiles Hi Nick, when the contentLength is set by the user, the SDK will not buffer the stream into memory, instead the user's stream will be used. What happens is sometimes the users pass in a stream that cannot be read properly by the service because it is not configured correctly. For example, if you created a stream via fs.createReadStream() but you did not pass in the proper highWaterMark, then fs.createReadStream will default the highWaterMark to 64kb. But if your stream is actually bigger 64KB, then this will be an issue because your stream size is actually bigger than the highWaterMark. And when you send this to the service, it will cause a socket hangup. 

We do allow the option for users to have their stream read into buffer even if contentLength is passed in. In the putObjectRequest, you can turn on retryConfiguration.backupBinaryBody to true. Here is an example:
````
    const putObjectRequest: os.requests.PutObjectRequest = {
      namespaceName: namespace,
      bucketName: bucket,
      putObjectBody: objectData,
      objectName: object,
      contentLength: stats.size,
      retryConfiguration: {
        backupBinaryBody: true // If this is true, all bodies will be buffered into memory.
      }
    };
````

**Comment by nicholasgiles** [comment]
@waruwaruwaru If the files are being loaded into memory then I don't think this works for us (as I previously mentioned in https://github.com/oracle/oci-typescript-sdk/issues/50#issuecomment-776249101). We cannot afford to load potentially very large files into memory in order to be able to upload them to Object Storage. I tried it with a 1.5G file and I got an "Invalid array length" exception - not sure whether or not this means it's out of memory. 

We have been using the AWS SDK in with OCI Object Storage in S3 compatibility mode and this allows us to pass a stream to the upload method and it does not seem to have the same memory load that the oci-objectstorage#putObject method does.

**Comment by waruwaruwaru** [comment]
@nicholasgiles for AWS SDK S3.upload(), it also buffer streams into memory but they do it in chunks so you do not read it all at once. We also have the same concept in our Upload Manager where the SDK will buffer them in chunks, can you try using that and see that can fix large files?

**Comment by waruwaruwaru** [comment]
Hey @nicholasgiles, did you get a chance to try Upload Manager? Let me know if that can help resolve the issue. Thanks!

**Comment by waruwaruwaru** [comment]
Hi @nicholasgiles, just wanted to check in again if you were able to resolve this issue using Upload Manager?

**Comment by waruwaruwaru** [comment]
@nicholasgiles I will be closing this issue, if you have the time to try upload manager and run into any issues, please feel free to re-open the issue and I'll be happy to help. Thanks again for reporting this issue.
