### ISSUE TITLE
objectstorage: headObject() and getObject() do not return opcMeta

### ISSUE THREAD

**Issue by mkroutikov** [oracle/oci-typescript-sdk#52]
https://github.com/oracle/oci-typescript-sdk/blob/master/lib/objectstorage/lib/client.ts#L2144

^^ this is a wrong way to iterate headers. You also fail to strip `opc-meta-` prefix when assigning to `opcMeta` object.

**Comment by waruwaruwaru** [comment]
Hi @mkroutikov, Thanks for pointing out the header iteration, I will get that fixed. As for the opc-meta- prefix, the SDK do not strip `opc-meta` when assigning to `opcMeta` object. The SDK sends back what the server gives. Let me know if this answers your question.

**Comment by waruwaruwaru** [comment]
Hi @mkroutikov, I will close this issue as I have not heard back. Feel free to re-open this issue if there any more questions.
