### ISSUE TITLE
Incorrect types for usageapi

### ISSUE THREAD

**Issue by squarebracket** [oracle/oci-typescript-sdk#53]
I was going to submit a PR, but the files say they're automatically generated at the top, so I don't know if this code is actually written by people. I can still submit a PR if you wish.

There are two problems with the types in the usageapi package.

First, [the `tags` property of `UsageSummary`](https://github.com/squarebracket/oci-typescript-sdk/blob/e93cf2c67aa8d7f0f40211beb73ca45753d23f1d/lib/usageapi/lib/model/usage-summary.ts#L132) should not be optional. From what I can tell, tags are always returned. I tested this is the case in the following scenarios:
- `groupByTag` is `[{namespace: 'mycompany', key: 'project'}]`
- `groupBy` is `['service']`
- neither `groupBy` nor `groupByTag` is used
- `filter` is `{operator: 'NOT', tags: [{namespace: 'mycompany', key: 'project'}]`

Second, the [`RequestSummarizedUsagesDetails` interface doesn't include `groupByTag`](https://github.com/squarebracket/oci-typescript-sdk/blob/e93cf2c67aa8d7f0f40211beb73ca45753d23f1d/lib/usageapi/lib/model/request-summarized-usages-details.ts). Obviously, it should. Since `groupBy` and `groupByTag` are mutually exclusive, you've got a couple options here:
1. Set both to optional and handle the mutual exclusion in the client code (or, I suppose, just let the server reject it -- see below).
2. Make a type that enforces only one or the other. You can do this with some unions and intersections that enforce `never` on the other property:
```typescript
export interface GroupBy {
  /**
   * Aggregate the result by. Mutually exclusive with `groupByTag`.
   * example:
   *   `[\"service\"]`
   */
  "groupBy"?: Array<string>;
  "groupByTag"?: never;
}

export interface GroupByTag {
  /**
   * Group by a specific tag key. Provide the namespace and key in the tag object.
   * Only supports one tag in the list. Mutually exclusive with `groupBy`.
   * For example:
   * `[{"namespace":"oracle", "key":"createdBy"}]`
   */
  "groupByTag"?: Array<Tag>;
  "groupBy"?: never;
}

// Using Omit here to show you'd remove `groupBy` from the existing interface
export type RequestSummarizedUsagesDetailsActual = Omit<RequestSummarizedUsagesDetails, 'groupBy'> & (GroupBy | GroupByTag);
```

This is nice because an IDE will know it fails the type check, though `tsc` doesn't understand XORs natively so you end up with an error message like:
```
Type '{ granularity: RequestSummarizedUsagesDetails.Granularity.Daily; tenantId: string; timeUsageEnded: Date; timeUsageStarted: Date; groupBy: string[]; groupByTag: { ...; }[]; }' is not assignable to type 'RequestSummarizedUsagesDetailsActual'.
  Type '{ granularity: RequestSummarizedUsagesDetails.Granularity.Daily; tenantId: string; timeUsageEnded: Date; timeUsageStarted: Date; groupBy: string[]; groupByTag: { ...; }[]; }' is not assignable to type 'Pick<RequestSummarizedUsagesDetails, "granularity" | "queryType" | "tenantId" | "timeUsageEnded" | "timeUsageStarted" | "compartmentDepth" | "filter"> & GroupByTag'.
    Type '{ granularity: RequestSummarizedUsagesDetails.Granularity.Daily; tenantId: string; timeUsageEnded: Date; timeUsageStarted: Date; groupBy: string[]; groupByTag: { ...; }[]; }' is not assignable to type 'GroupByTag'.
      Types of property '"groupBy"' are incompatible.
        Type 'string[]' is not assignable to type 'undefined'.
```

Also worth mentioning: if you pass both `groupBy` and `groupByTag` to the API, you actually get an error message that references an incorrect parameter:
```
{
  "code" : "InvalidParameter",
  "message" : "groupBy must be null when groupByTagKey isn't empty"
}
```

Obviously, that should be `groupByTag`, not `groupByTagKey`. If you try to make a request that includes `groupByTagKey`, it rejects the request saying it's an invalid parameter.

**Comment by waruwaruwaru** [comment]
@squarebracket thank you for reaching out. For the first problem, the Usage API doc (https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/UsageSummary/) "tags" is not required, so our SDK made it as optional. For the second problem, I will have an engineer from Usage team take a look at this.

**Comment by squarebracket** [comment]
@waruwaruwaru is `UsageSummary` used somewhere other than the result of the `RequestSummarizedUsages` call? Perhaps it is an error in your API spec since it is returned in every call and/or `required: no` means the returned value may be null?

**Comment by waruwaruwaru** [comment]
@squarebracket At the moment I only see `UsageSummary` used in `RequestSummarizedUsages`.`required: no`, means it might not always return by the service. That means the returned response object might not always have that field. If the server does not return that field, then the SDK will not have that field in the response object. The SDK does not return response object with a field with `null` or `undefined` value if the server does not send back that field. Let me know if this answers your question :)

**Comment by davidkhala** [comment]
By the way, I also bear same question that since `the files say they're automatically generated at the top, so I don't know if this code is actually written by people`, how could we contributre a PR to it?

**Comment by waruwaruwaru** [comment]
Hey @davidkhala, 
These files are based on what the service API spec are defined so the SDK cannot change it unless the Usageapi service team changes their spec. But the latest SDK shows OP's 2nd question was addressed: groupByTag is a field in the RequestSummarizedUsagesDetails interface.

As for the first question about why tag is optional, that is also something that is defined by the Usageapi service team.

**Comment by jodoglevy** [comment]
@davidkhala  I've going to close this issue based on the response provided by @waruwaruwaru  and that we haven't heard back from you in quite a while. If you are still hitting this problem however, please feel free to reopen this
