### ISSUE TITLE
isomorphic-fetch - outdated - denial of service

### ISSUE THREAD

**Issue by jhult** [oracle/oci-typescript-sdk#59]
isomorphic-fetch relies on a vulnerable version of node-fetch. It should be updated. See below for details.

node-fetch  <=2.6.0 || 3.0.0-beta.1 - 3.0.0-beta.8
Denial of Service - https://npmjs.com/advisories/1556

isomorphic-fetch  2.0.0 - 2.2.1
  Depends on vulnerable versions of node-fetch
  node_modules/isomorphic-fetch
    oci-common  *
    Depends on vulnerable versions of isomorphic-fetch

**Comment by waruwaruwaru** [comment]
@jhult thank you for reporting, I will take a look into this issue.

**Comment by jhult** [comment]
@waruwaruwaru, any updates on this?

**Comment by waruwaruwaru** [comment]
Hi @jhult, the next release (May 4th, 2021) will have the upgraded version of isomorphic-fetch (v3.0.0).

**Comment by waruwaruwaru** [comment]
The latest version of the SDK (v1.19.2) now uses isomorphic-fetch v3.0.0. If there is any issues please feel free to reopen this issue. Thank you for reporting this issue. @jhult
