### ISSUE TITLE
Question about authentication provider to use object storage.

### ISSUE THREAD

**Issue by moimstone-Crong** [oracle/oci-typescript-sdk#61]
Hi,
I'm using oci api library to make my application access object storage. I followed examples and accomplished my mission. But, I had to provide authencation information in file form. Examples use ConfigFileAuthenticationDetailsProvider() to provide authencation information. 

But, I want to inject all of these properties in string form(environment variables - kubernetes configmap).
Do you have any alternative APIs to meet my needs?

Thank you

**Comment by jodoglevy** [comment]
Hi - yes we support doing this. See the https://github.com/oracle/oci-typescript-sdk/blob/master/examples/typescript/simple-authentication.ts example

**Comment by waruwaruwaru** [comment]
Hi @moimstone-Crong did the example provided by @jodoglevy resolved your issue?

**Comment by moimstone-Crong** [comment]
Hi guys, I really appreiciate it. Thank you
