### ISSUE TITLE
OCI-objectstorage is too dependent on fs.createReadStream to transfer objects

### ISSUE THREAD

**Issue by nms2019** [oracle/oci-typescript-sdk#66]
Most App Dynos do not allow storage of even temporary files( even small ones) on their servers.  Most use Amazon S3 as their primary way around this by sending the created file to S3 and then accessing the data, essentially what most of your Use Case requires.   Also because the code is dependent on fs. the function will always add this header:
[ '----------------------------622545709057705753853273\r\nContent-
Disposition: form-data; name="file"; filename="tickets.pdf"\r\nContent-Type: application/pdf\r\n\r\n' to the blob data. 

 Obviously Object Storage is able to decipher this, I suggest an enhancement that will allow you to send either formData or as a generic blob object from the web app either client side or via backend to the storage and not be reliant on the fs feature to get data to your object store since fs requires a file path to work, if you can't store a file, you can't leverage fs.   

If there is a work around of not having the createReadStream format in the putObjectBody: prop I would love to hear it.

Thanks

Brian

**Comment by nms2019** [comment]
Any update or ETA? I have a few projects that we would like to use Oracles Object Storage, but all are hosting platforms have ephemeral filesystems making the reliance on fs.createReadStream useless for creating streams.

**Comment by waruwaruwaru** [comment]
Hi Brian,
Can you try passing in a Blob in the request? Currently our putObject body do allow Blob (https://github.com/oracle/oci-typescript-sdk/blob/master/lib/objectstorage/lib/request/put-object-request.ts#L45). But our SDK currently do not have the ability to calculate the content-length of a Blob so you would need to calculate the content-length of the Blob. Let me know if that works or if you run into any issues.

**Comment by nms2019** [comment]
So in my bucket I get the following when I try to pass it as a blob see below, the pdf does not transfer, the file on April 9th works as a fs.createReadStream: 

![Screenshot 2021-05-10 225123](https://user-images.githubusercontent.com/46869289/117765351-a7bf7600-b1e2-11eb-9834-ca975f385ea6.png)

code is as follows: 

```

const blob = await asPDF.toBlob()


    
    const bucketName = ociprovider.bucketName

   const objectStorageClient = new ObjectStorageClient({
      authenticationDetailsProvider: authProvider
    })

    objectStorageClient.region = Region.US_ASHBURN_1
    const request = {}
    const response = await objectStorageClient.getNamespace(request)
    const namespace = response.value
const putObjectRequest = {
      namespaceName: namespace,
      bucketName: bucketName,
      putObjectBody: blob,
      contentType: 'application/pdf',
      objectName: customer_number + '/' + file_name +'.pdf',
      contentLength: blob.size
    
    }
const putObjectResponse = await objectStorageClient.putObject(putObjectRequest)
    console.log('Put Object executed succesfully' + putObjectResponse)


```

Would love for this too work as a blob but not sure what I'm missing(also tried contentType as the default 'application/octet-stream' but same result).  Please help.

**Comment by nms2019** [comment]
The blob size is 17,540.  Yes its a blob at least I think so, VSC recognizes it as a Blob. But to be sure here is the code that takes the PDF document and converts to a blob:

```
async function toBlob() {
    await container.render();
    const stream = container.instance.pipe(BlobStream());
    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        try {
          const blob = stream.toBlob('application/pdf');
          callOnRender({
            blob
          });
          resolve(blob);
        } catch (error) {
          reject(error);
        }
      });
      stream.on('error', reject);
    });
  }
```

Tried first by changing the contentType to application/json, then putObjectBody: blob.stream(), then changed contentType: application/pdf, with the blob.stream() as the putObjectBody, still no joy.

**Comment by waruwaruwaru** [comment]
@nms2019, what library are you using to create a Blob? I think some NPM packages have their own way of defining a blob so its not quite the same as the one from (https://developer.mozilla.org/en-US/docs/Web/API/Blob). What does blob.stream() return back? It should return back a ReadableStream (https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream)

**Comment by nms2019** [comment]
Can you provide the code to transform a blob to a buffer?

**Comment by waruwaruwaru** [comment]
You will first need to get the stream from the blob by doing const readableStream = blob.stream(). This will return a ReadableStream. 

`
// Get the ReadableStream
const readableStream = blob.stream()
// Create a Reader
const reader = data.getReader();
const chunks = [];
while (true) {
  //While not done, keep reading chunks off the reader
  const { done, value } = await reader.read();
  if (done) return;
  chunks.push(value)
}
// Finally concat chunks into our buffer
const buffer = Buffer.concat(chunks)
`

This is actually what we do in our SDK's UploadManager and I will release this code next week if you want to wait to use our Upload Manager instead.

**Comment by nms2019** [comment]
I'll wait to use the upload manager. :-) Let me know when it comes out.

**Comment by waruwaruwaru** [comment]
@nms2019 the upload manager should now be able to support Blob type of streams, here is an example of our upload manager code: 
https://github.com/oracle/oci-typescript-sdk/blob/master/examples/typescript/uploadmanager.ts
A minor tweak you can do since you are using a blob stream, instead of using filePath (like in the example), you can pass in your stream object directly like so:
````
await uploadManager.upload(
  {            
    content: {              
      stream: myBlob  // pass in Blob object here      
    },            
    requestDetails: {              
      namespaceName: namespaceName,              
      bucketName: bucketName,              
      objectName: objectName            
    },
  }          
    callback        
);

**Comment by nms2019** [comment]
This worked, but I had to use blob.stream() instead of just blob,

![image](https://user-images.githubusercontent.com/46869289/120027367-20c31980-bfa8-11eb-99cc-b274ecff9397.png)

**Comment by waruwaruwaru** [comment]
What error do you get if you pass in the blob instead of blob.stream()?

**Comment by nms2019** [comment]
There was no error it just was the file with the 0 kbs.

**Comment by nms2019** [comment]
Let me see if I can't play around with also I added in the code:

`console.log(blob instanceof Blob)`
which always came back as true.

**Comment by waruwaruwaru** [comment]
Does `console.log(blobl.stream() instanceof ReadableStream)` return true?

**Comment by nms2019** [comment]
I've got some other deadlines due today, so I'm going to work on this again on Monday... but I will try all three and verify.  However happy it works, and just tried it on heroku servers and it works.   Thank you.

**Comment by waruwaruwaru** [comment]
No problem. Sometimes users have blob objects that are not exactly the same as the one from https://developer.mozilla.org/en-US/docs/Web/API/Blob. I know some NPM package library implements a blob object differently and its hard to know exactly how each library implement their blob object.

**Comment by waruwaruwaru** [comment]
Hey @nms2019, I have not heard back from this ticket in a while. It looks like you have a working solution, if you would like to debug this further, please feel free to reopen this issue. Thank you.
