### ISSUE TITLE
"OciError: unknown reason." during headBucket request

### ISSUE THREAD

**Issue by moimstone-Crong** [oracle/oci-typescript-sdk#69]
Hello,

I wrote my application creating bucket and creating preauthenciated request with you examples.
And it works alright.
This time, I wanted to check if the bucket already exists. So I added code snippets below.
```
try {
    const bucketName = config.services.storagemgmt.bucketPrefix + reqSvc;
    console.log('bucketName ', bucketName);
    const headBucketReq: os.requests.HeadBucketRequest = {
          namespaceName: this.namespace,
          bucketName
    };
    console.log('headBucketReq --------', headBucketReq);
    const hb = await this.client.headBucket(headBucketReq);
    console.log('hb-----------------------', hb);
} catch (e) {
    console.error('error caught...------', e);
    return null;
}
```
and its output is
```
headBucketReq -------- { namespaceName: 'cnkxfskwuk3c', bucketName: 'cronghomedevicemgmt' }
Cannot parse data into JSON
error caught...------
OciError: unknown reason.
    at Object.handleErrorResponse (/Users/cronglee/project/smartwork/svc/storagemgmtservice/src/node_modules/oci-common/lib/helper.js:41:16)
    at GenericRetrier.<anonymous> (/Users/cronglee/project/smartwork/svc/storagemgmtservice/src/node_modules/oci-common/lib/retrier.js:76:54)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cronglee/project/smartwork/svc/storagemgmtservice/src/node_modules/oci-common/lib/retrier.js:9:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 404,
  serviceCode: 'unknown code',
  opcRequestId: 'icn-1:5NfTpujr6Ds0INSN1FyWQXTNF9_S8RFK-3Npexsnb-Uyj75BrKzGKYfRKq-iRxJW'
}
```
I compared my code with the example in https://docs.oracle.com/en-us/iaas/tools/typescript-sdk-examples/1.10.0/objectstorage/HeadBucket.ts.html. But I don't see any big difference.

What is wrong with me?

Thank you.

**Comment by waruwaruwaru** [comment]
Hi @moimstone-Crong, the sample code you wrote looks fine. I've ran the same code on my end and it works on my end. 404 could mean that it could not find your resource. Can you check if the bucket exists in your namespace?

**Comment by moimstone-Crong** [comment]
Hello, 

What a strange!
I doublecheked I could create the buckets and preauthencatedrequests with the same client(this.client) instance in my code.

I think the error message "Cannot parse data into JSON" is more suspicious. Where is it from? The error message is occurred whitin "await this.client.headBucket(headBucketReq);"

For your fast support I'd like to give you my file. 
'''
import {Request, Response} from 'express';
import common = require('oci-common');
import os = require('oci-objectstorage');
import shortid from 'shortid';

import { isNull } from 'lodash';
import config from '../../../config';
import OSFile from '../../store/OSFile';
import OSFileService from './OSFileService';
const FILESERVICE = new OSFileService();

/*
 * Oci API initialize
 */

const region: common.Region = common.Region.AP_SEOUL_1;
const provider = new common.SimpleAuthenticationDetailsProvider(
    config.services.storagemgmt.tenancy,
    config.services.storagemgmt.user,
    config.services.storagemgmt.fingerprint,
    config.services.storagemgmt.privateKey,
    null,
    region
  );

const compartmentId: string = config.services.storagemgmt.ocicompartmentId;

export class OperateFileManagement {
    private client: os.ObjectStorageClient;
    private namespace: string;
    constructor() {
        this.client = new os.ObjectStorageClient({ authenticationDetailsProvider: provider });
    }

    public async initializeOci() {
        try {
            const request: os.requests.GetNamespaceRequest = {};
            const response = await this.client.getNamespace(request);
            this.namespace = response.value;
        } catch (e) {
            console.error('Error executing your request ' + e);
        }
    }

    public async createUploadRequest(req: Request, res: Response): Promise<any> {
        try {
            const reqUser = req.body.user;
            const reqSvc = req.body.svc;

            const newFile = new OSFile();
            await this.checkBucket(req, res);

            newFile.bucket = await this.createNewBucket('crong-home-storage-test');
            newFile.objectname = this.genObjectName();
            newFile.createdByUser = reqUser;
            newFile.createdBySvc = reqSvc;
            newFile.confirmed = false;

            const {uri} = await this.requestPreauthenticatedSign(newFile.bucket, newFile.objectname,
                'upload-' + newFile.objectname, 'W', false);

            const savedFile = await FILESERVICE.createOSFile(newFile);

            return {fId: savedFile.id, URL: uri + newFile.objectname};
        } catch (e) {
            console.error('error caught...------');
            console.error(e);
            return null;
        }
    }

    public async createDownloadRequest(req: Request, res: Response): Promise<any> {
        try {
            let id;
            const fileIdInQuery = req.body.fileid;

            if (Array.isArray(fileIdInQuery)) {
                id = fileIdInQuery[0];
            } else {
                id = fileIdInQuery;
            }

            const savedFile = await FILESERVICE.getFileById(id);

            if (savedFile) {
                let bPermanent: boolean = false;

                if ( req.body.svc === 'user') {
                    bPermanent = true;
                }
                const {uri} = await this.requestPreauthenticatedSign(savedFile.bucket, savedFile.objectname,
                    'downalod-' + savedFile.objectname, 'R', bPermanent);

                return {fId: savedFile.id, URL: uri};
            } else {
                return null;
            }
        } catch (e) {
            console.error(e);
            return null;
        }

    }

    private async checkBucket(req: Request, res: Response): Promise<any> {
        try {
            const reqSvc = req.body.svc;

            const bucketName = config.services.storagemgmt.bucketPrefix + reqSvc;
            console.log('bucketName ', bucketName);
            const headBucketReq: os.requests.HeadBucketRequest = {
                namespaceName: this.namespace,
                bucketName
            };
            console.log('headBucketReq --------', headBucketReq);
            const hb = await this.client.headBucket(headBucketReq);
            console.log('hb-----------------------', hb);
            return hb;
        } catch (e) {
            console.error(e)
            return null;
        }
    }

    private genObjectName() {
        return `MSWObj_${Date.now().toString()}_${shortid.generate()}`;
    }

    private genBucketName() {
        // MSWB stands for Moimstone SmartWork Bucket.
        return `MSWB_${Date.now().toString()}_${shortid.generate()}`;
    }

    private async createNewBucket(bucket: string): Promise<string> {
        try {
            if (isNull(bucket)) {
                bucket = this.genBucketName();
            }

            console.log(`Creating the bucket. [${bucket}]`);
            const bucketDetails: os.models.CreateBucketDetails = {
                name: bucket,
                compartmentId
            };
            const createBucketRequest: os.requests.CreateBucketRequest = {
                namespaceName: this.namespace,
                createBucketDetails: bucketDetails
            };
            await this.client.createBucket(createBucketRequest);
            return bucket;
        } catch (e) {
            console.error('Error executing your request ' + e);
        }
        return null;
    }

    private async requestPreauthenticatedSign(bucket: string,
                                              objectName: string,
                                              reqName: string, RW: string, bPermanent: boolean): Promise<any> {
        try {
            console.log('bPermanent in requestPreauthenticatedSign is ', bPermanent);

            if (isNull(RW) || (RW !== 'R' && RW !== 'W')) {
                throw new Error('Unknown access type');
            }

            if (isNull(bucket)) {
                throw new Error('bucket must be provided.');
            }

            if (RW === 'R' && (isNull(objectName) || objectName === '')) {
                throw new Error('objectName must be provided for download request.');
            }

            // set expiration date;

            const preAuthExpires = new Date();
            let createPreauthenticatedRequestDetails: os.models.CreatePreauthenticatedRequestDetails;

            if (isNull(reqName)) {
                reqName = this.genObjectName();
            }

            if (RW === 'R') {
                console.log('download request for long erm ', bPermanent);
                if (bPermanent) {
                    preAuthExpires.setMonth(preAuthExpires.getMonth() + 12);
                } else {
                    preAuthExpires.setMinutes(preAuthExpires.getMinutes() + 10);
                }

                createPreauthenticatedRequestDetails = {
                    name: reqName,
                    objectName,
                    accessType: os.models.CreatePreauthenticatedRequestDetails.AccessType.ObjectRead,
                    timeExpires: preAuthExpires
                };
            } else {
                preAuthExpires.setMinutes(preAuthExpires.getMinutes() + 10);

                createPreauthenticatedRequestDetails = {
                    name: reqName,
                    accessType: os.models.CreatePreauthenticatedRequestDetails.AccessType.AnyObjectWrite,
                    timeExpires: preAuthExpires
                };
            }

            const createPreauthenticatedRequest: os.requests.CreatePreauthenticatedRequestRequest = {
                namespaceName: this.namespace,
                bucketName: bucket,
                createPreauthenticatedRequestDetails
            };

            const createPreauthenticatedResponse =
                await this.client.createPreauthenticatedRequest(createPreauthenticatedRequest);
            // console.log('Create Preauthenticated executed successfully');
            // console.log(createPreauthenticatedResponse);
            return {uri: this.client.endpoint + createPreauthenticatedResponse.preauthenticatedRequest.accessUri};

        } catch (e) {
            console.error('Error executing your request ' + e);
        }
        return null;
    }

}

export default OperateFileManagement;

'''

Thank you

**Comment by waruwaruwaru** [comment]
@moimstone-Crong, can you check to see if that bucket indeed exists on your namespace? You can check via console webpage. The console.log for "Cannot parse data into JSON" comes from here: https://github.com/oracle/oci-typescript-sdk/blob/master/lib/common/lib/helper.ts#L46. This code tries to handle your response error by reading in the response body as a text. It then tries to see if it can parse that text into a JSON, it it cannot, then it will simply return the text. But in your case, you're getting back "unknown reason", that would mean the response error did not have a message body.

**Comment by moimstone-Crong** [comment]
I check if the bucket already exists or not. I sure that there is no bucket named with I tried to check.
By the way, as far as I understood from document, _HeadBucketRequest_ method is to see where the bucket exists or not, right? 
If the bucket exists, _HeadBucketRequest_ should return the result of it. Not occurring error like that.

Thanks

**Comment by waruwaruwaru** [comment]
For HeadBucketRequest, if the bucket does not exist then it will send a 404. If you got a statusCode: 404 and you know that bucket does not exist then the error you got is the correct behavior. At the moment the SDK does not handle head request error very well. We will work on sending back a better error for head request errors.

**Comment by moimstone-Crong** [comment]
Oh I see.

Could you let me know when the SDK is ready?

**Comment by waruwaruwaru** [comment]
Hey @moimstone-Crong, we will work on providing a better error message for head request errors. But as for the result you got back (statusCode: 404), that should be the expected response. Does that help unblock your problem?

**Comment by moimstone-Crong** [comment]
Hi @waruwaruwaru, I guess I cannot resolve this exception by myself. I don't know how to retrieve status 404 code from that exception. I'm not a super hero in typescript. If you provide code snippets how to retrieve staus code 404 from that exception, I can hang on until you guys fix it. Can you help me?

**Comment by waruwaruwaru** [comment]
Hi @moimstone-Crong, on your createNewBucket function's catch block, you can return e.statusCode to return back the status code. 
`
catch (e) {
    console.error(e)
    return e.statusCode;
}
`

**Comment by moimstone-Crong** [comment]
Hi @waruwaruwaru .
It's clear now.
Thank you
