### ISSUE TITLE
[Document]difference and usage for vault/kms documents

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-typescript-sdk#80]
I cannot find clear documentation on how to use oci-ts-sdk to interact with OCI Vault. Should it be oci-vault or oci-keymanagement?

**Comment by jodoglevy** [comment]
Hi @davidkhala  - it depends on what action you are trying to accomplish. What are you trying to use the SDK to do, against OCI Vault?

**Comment by jodoglevy** [comment]
@davidkhala for signing, please see https://docs.oracle.com/en-us/iaas/api/#/en/key/release/SignedData/Sign. For verifying, please see https://docs.oracle.com/en-us/iaas/api/#/en/key/release/VerifiedData/Verify.

On either page, if you scroll down to the `Examples` section, and then click on `TypeScript SDK`, you should be able to see an example on how to use these operations.

**Comment by jodoglevy** [comment]
@davidkhala  I'm going to close this since we haven't heard from you in quite a while, and I think I provided solution to your question above. But please feel free to reopen this if your issue is not resolved.
