### ISSUE TITLE
oci-objectstorage Upload Manager doesn't work with empty files

### ISSUE THREAD

**Issue by kdclaw3** [oracle/oci-typescript-sdk#96]
When trying to use upload manager to upload an empty file we receive the error:

node 12.16.1
oci-sdk versions **1.19.5 & 2.3.1**

Failed due to RangeError [ERR_OUT_OF_RANGE]: The value of "end" is out of range. It must be >= 0 and <= 2 ** 53 - 1. Received -1

**Comment by jodoglevy** [comment]
Thanks @kdclaw3  for reporting - we'll take a look

**Comment by waruwaruwaru** [comment]
Hi @kdclaw3, I was able to upload a 0 byte empty file on my end with the latest SDK (v2.3.1). The steps I took was **touch myZeroByteExampleFile**. This created an empty file of 0 byte. I was able to upload this file successfully. Can you double check if this issue occurs on v2.3.1? If it does occur in v.2.3.1 can you give a stackTrace of the error or the your code? Thanks!

**Comment by kdclaw3** [comment]
@waruwaruwaru, Sorry, I retested, this is only happening on v1.19.5. It is working on 2.3.1. You can close the issue. We are stuck on 1.19.5 until issue #90 is fixed.

**Comment by jodoglevy** [comment]
@kdclaw3  thanks
