### ISSUE TITLE
Failed to parse (unnamed) on Private Key

### ISSUE THREAD

**Issue by Manuelandro** [oracle/oci-typescript-sdk#98]
Hello, we just moved our stack to Oracle Cloud and I'm setting up the deployment to object-storage.
When I pass the configuration i get this error, I don't know if it is a bug or I'm doing something stupid.

Note that I tried both with Oracle generated pem and with local generated rsa

```
KeyParseError: Failed to parse (unnamed) as a valid auto format key: Failed to auto-detect format of key
    at Object.PrivateKey.parse [as parsePrivateKey] (/Users/user/Angular/frontend/node_modules/sshpk/lib/private-key.js:197:10)

```

```
const TENANCY = 'ocid1.tenancy.oc1........'
const USER = 'ocid1.user.oc1........'
const REGION = 'us-ashburn-1'
const FINGERPRINT = 'f7:40:4d:96:79..............'
const KEY_FILE = '~/Desktop/oracle/user/-09-29-10-43.pem'

const client = new ObjectStorage.ObjectStorageClient({
    authenticationDetailsProvider:
        new common.SimpleAuthenticationDetailsProvider(
            TENANCY,
            USER,
            FINGERPRINT,
            KEY_FILE,
            undefined,
            common.Region.fromRegionId(REGION),
        ),
})

```

**Comment by jodoglevy** [comment]
Hi @Manuelandro. A few questions:
- When you say "Oracle generated pem" - do you mean a keypair downloaded from the OCI Console experience in the web browser?
- I see your pem file name starts with a dash "-". Does it happen to work if you remove the dash from the file name?
- I see "Angular" mentioned in the stack trace -- are you using the SDK in NodeJS, or in a web browser context?

**Comment by Manuelandro** [comment]
> Hi @Manuelandro. A few questions:
> 
> * When you say "Oracle generated pem" - do you mean a keypair downloaded from the OCI Console experience in the web browser?
> * I see your pem file name starts with a dash "-". Does it happen to work if you remove the dash from the file name?
> * I see "Angular" mentioned in the stack trace -- are you using the SDK in NodeJS, or in a web browser context?

hi @jodoglevy:

• yes, I meant the keypair from the OCI console
• yes, i tried also with a simple name like "oci_private_key.pem"
• angular is the frontend source but I'm using the module in a node enviroment as an "afterbuild script"

**Comment by waruwaruwaru** [comment]
Hi @Manuelandro, since you are using SimpleAuthenticationDetailsProvider, we do not take in private key as the file path. You would need to pass in the actual full string. The SDK would help you read the file path if you used ConfigFileAuthenticationDetailsProvider.

**Comment by Manuelandro** [comment]
> Hi @Manuelandro, since you are using SimpleAuthenticationDetailsProvider, we do not take in private key as the file path. You would need to pass in the actual full string. The SDK would help you read the file path if you used ConfigFileAuthenticationDetailsProvider.

thanks it did help
